src/AppBundle/Entity/Comment.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use UserBundle\Entity\User;
/**
 * Comment
 *
 * @ORM\Table(name="comment_table")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var bool
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    private $enabled;







        /**
     * @ORM\ManyToOne(targetEntity="Status", inversedBy="comments")
     * @ORM\JoinColumn(name="status_id", referencedColumnName="id", nullable=true)
     */
    private $status;




    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="comments")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    private $user;
    public function __construct()
    {
        $this->created= new \DateTime();

    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * Set content
     *
     * @param string $content
     * @return Comment
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }
    public function getContentclear()
    {
        return base64_decode($this->content);
    }
    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Comment
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return Comment
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }
    /**
    * Get user
    * @return  
    */
    public function getUser()
    {
        return $this->user;
    }
    
    /**
    * Set user
    * @return $this
    */
    public function setUser(User $user)
    {
        $this->user = $user;
        return $this;
    }
    /**
     * Get enabled
     *
     * @return boolean 
     */
    public function getEnabled()
    {
        return $this->enabled;
    }


  	/**
  	* Get status
  	* @return  
  	*/
  	public function getStatus()
  	{
  	    return $this->status;
  	}
  	
  	/**
  	* Set status
  	* @return $this
  	*/
  	public function setStatus($status)
  	{
  	    $this->status = $status;
  	    return $this;
  	}
  
}

src/AppBundle/Form/GifType.php
<?php
namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\Ed;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
class GifType extends AbstractType
{
   public function buildForm(FormBuilderInterface $builder, array $options)
    {
         $builder->add('title',"text",array("label"=>"Title"));
         $builder->add('description',null,array("label"=>"description"));
         $builder->add('enabled',null,array("label"=>"Enabled"));
         $builder->add('comment',null,array("label"=>"Enabled comments"));
         $builder->add('tags',null,array("label"=>"Tags (Keywords)"));

         $builder->add("categories",'entity',
                      array(
                            'class' => 'AppBundle:Category',
                            'expanded' => true,
                            "multiple" => "true",
                            'by_reference' => false
                          )
                      );
         $builder->add("languages",'entity',
                      array(
                            'class' => 'AppBundle:Language',
                            'expanded' => true,
                            "multiple" => "true",
                            'by_reference' => false
                          )
                      );
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $article = $event->getData();
            $form = $event->getForm();
            if ($article and null !== $article->getId()) {
                 $form->add("filegif",null,array("label"=>"","required"=>false));
            }else{
                 $form->add("filegif",null,array("label"=>"","required"=>true));
            }
        });
        $builder->add('save', 'submit',array("label"=>"save"));
      }
      public function getName()
      {
          return 'Video';
      }
}
?>

src/AppBundle/Controller/StatusController.php
<?php
namespace AppBundle\Controller;
use AppBundle\Entity\Transaction;
use AppBundle\Entity\Status;
use AppBundle\Form\ImageType;
use AppBundle\Form\GifType;
use AppBundle\Form\QuoteType;
use AppBundle\Form\StatusReviewType;
use AppBundle\Form\QuoteReviewType;
use AppBundle\Form\VideoType;
use AppBundle\Form\VideoTypeUrl;
use MediaBundle\Entity\Media;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class StatusController extends Controller {
    function remove_emoji ($string="") {
    $string = str_replace(" ","736489290",$string);
     
     // PREG_REPLACE REMOVE ALL OTHER CHARACTERS THAT NOT AVAIALABLE IN PREG_REPLACE FIRST
     // PARAMETER YOU CANNOT UNDERSTAND FIRST PARAMETER YOU MUST READ PHP REGULAR EXPRESSION!
     $string = preg_replace('/[^A-Za-z0-9]/','',$string);
     
     //STRIP_TAGS REMOVE HTML TAGS
     $string=strip_tags($string,"");
      //HERE WE REMOVE WHITE SPACES AND RETURN IT
    
     $newString =  trim($string);
     $newString = str_replace("736489290"," ",$newString);

     return $newString;
    }
	public function addVideoAction(Request $request) {
		$video = new Status();
		$video->setType("video");
		$form = $this->createForm(new VideoType(), $video);
		$em = $this->getDoctrine()->getManager();

		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			if ($video->getFile() != null and $video->getFilevideo() != null) {
				$media = new Media();
				$media->setFile($video->getFile());
				$media->setEnabled(true);
				$media->upload($this->container->getParameter('files_directory'));

				$video->setMedia($media);

				$video_media = new Media();
				$video_media->setFile($video->getFilevideo());
				$video_media->setEnabled(true);
				$video_media->upload($this->container->getParameter('files_directory'));

				$video->setVideo($video_media);

				$video->setUser($this->getUser());
				$video->setReview(false);
				$video->setDownloads(0);
				$em->persist($media);
				$em->flush();

				$em->persist($video_media);
				$em->flush();

				$em->persist($video);
				$em->flush();
				$this->addFlash('success', 'Operation has been done successfully');
				return $this->redirect($this->generateUrl('app_status_index'));
			} else {
				$photo_error = new FormError("Required image file");
				$video_error = new FormError("Required video file");
				$form->get('file')->addError($photo_error);
				$form->get('filevideo')->addError($video_error);
			}
		}
		return $this->render("AppBundle:Status:video_add.html.twig", array("form" => $form->createView()));
	}


    public function editVideoAction(Request $request, $id) {
        $em = $this->getDoctrine()->getManager();
        $video = $em->getRepository("AppBundle:Status")->findOneBy(array("id" => $id, "review" => false));
        if ($video == null) {
            throw new NotFoundHttpException("Page not found");
        }
        $form = $this->createForm(new VideoType(), $video);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if ($video->getFile() != null) {
                $media = new Media();
                $media_old = $video->getMedia();
                $media->setFile($video->getFile());
                $media->setEnabled(true);
                $media->upload($this->container->getParameter('files_directory'));
                $em->persist($media);
                $em->flush();
                $video->setMedia($media);
                $em->flush();
                $media_old->delete($this->container->getParameter('files_directory'));
                $em->remove($media_old);
                $em->flush();
            }

            if ($video->getFilevideo() != null) {
                $video_media = new Media();
                $video_media_old = $video->getVideo();
                $video_media->setFile($video->getFilevideo());
                $video_media->setEnabled(true);
                $video_media->upload($this->container->getParameter('files_directory'));
                $em->persist($video_media);
                $em->flush();

                $video->setVideo($video_media);
                $em->flush();

                $video_media_old->delete($this->container->getParameter('files_directory'));
                $em->remove($video_media_old);
                $em->flush();
            }

            $em->persist($video);
            $em->flush();
            $this->addFlash('success', 'Operation has been done successfully');
            return $this->redirect($this->generateUrl('app_status_index'));
        }
        return $this->render("AppBundle:Status:video_edit.html.twig", array("form" => $form->createView()));
    }

public function addVideoUrlAction(Request $request) {
        $video = new Status();
        $video->setType("video");
        $form = $this->createForm(new VideoTypeUrl(), $video);
        $em = $this->getDoctrine()->getManager();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file_ext = substr(strrchr($video->getUrlvideo(), '.'), 1);
            switch ($file_ext) {
            case 'mp4':
                $file_type = "video/mp4";
                break;
            case 'webm':
                $file_type = "video/webm";
                break;
            default:
                $file_type = "none";
                break;
            }

            if ($file_type != "none") {
                if ($video->getFile() != null) {
                    $media = new Media();
                    $media->setFile($video->getFile());
                    $media->setEnabled(true);
                    $media->upload($this->container->getParameter('files_directory'));
                    $video->setMedia($media);

                    $video_media = new Media();
                    $video_media->setTitre($video->getTitle());
                    $video_media->setUrl($video->getUrlvideo());
                    $video_media->setExtension($file_ext);
                    $video_media->setType($file_type);
                    $video_media->setEnabled(false);

                    $video->setVideo($video_media);

                    $video->setUser($this->getUser());
                    $video->setReview(false);
                    $video->setDownloads(0);
                    $em->persist($media);
                    $em->flush();

                    $em->persist($video_media);
                    $em->flush();

                    $em->persist($video);
                    $em->flush();
                    $this->addFlash('success', 'Operation has been done successfully');
                    return $this->redirect($this->generateUrl('app_status_index'));
                } else {
                    $photo_error = new FormError("Required image file");
                    $form->get('file')->addError($photo_error);
                }
            } else {
                $type_error = new FormError("Url has video not supported");
                $form->get('urlvideo')->addError($type_error);
            }
        }
        return $this->render("AppBundle:Status:video_add_url.html.twig", array("form" => $form->createView()));
    }
    public function editVideoUrlAction(Request $request, $id) {
        $em = $this->getDoctrine()->getManager();
        $video = $em->getRepository("AppBundle:Status")->findOneBy(array("id" => $id, "review" => false));
        if ($video == null) {
            throw new NotFoundHttpException("Page not found");
        }
        $videourl = $video->getVideo()->getUrl();
        $video->setUrlvideo($videourl);
        $form = $this->createForm(new VideoTypeUrl(), $video);
        $form->handleRequest($request);

        $file_ext = substr(strrchr($video->getUrlvideo(), '.'), 1);
        switch ($file_ext) {
        case 'mp4':
            $file_type = "video/mp4";
            break;
        case 'webm':
            $file_type = "video/webm";
            break;
        default:
            $file_type = "none";
            break;
        }

        if ($file_type != "none") {

            if ($form->isSubmitted() && $form->isValid()) {
                if ($videourl != $video->getUrlvideo()) {

                    $video_media = new Media();
                    $video_media->setTitre($video->getTitle());
                    $video_media->setUrl($video->getUrlvideo());
                    $video_media->setExtension($file_ext);
                    $video_media->setType($file_type);
                    $video_media->setEnabled(false);

                    $video_media_old = $video->getVideo();
                    $em->persist($video_media);
                    $em->flush();

                    $video->setVideo($video_media);
                    $em->flush();

                    $video_media_old->delete($this->container->getParameter('files_directory'));
                    $em->remove($video_media_old);
                    $em->flush();
                }
                if ($video->getFile() != null) {
                    $media = new Media();
                    $media_old = $video->getMedia();
                    $media->setFile($video->getFile());
                    $media->setEnabled(true);
                    $media->upload($this->container->getParameter('files_directory'));
                    $em->persist($media);
                    $em->flush();
                    $video->setMedia($media);
                    $em->flush();
                    $media_old->delete($this->container->getParameter('files_directory'));

src/AppBundle/Resources/views/Status/delete.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
<div class="container-fluid">
	<div class="swal2-modal swal2-show" style="display: block; width: 500px; padding: 20px; background: rgb(255, 255, 255); min-height: 332px;" tabindex="-1">
	    <ul class="swal2-progresssteps" style="display: none;"></ul>
	    <div class="swal2-icon swal2-error" style="display: none;"><span class="x-mark"><span class="line left"></span><span class="line right"></span></span>
	    </div>
	    <div class="swal2-icon swal2-question" style="display: none;">?</div>
	    <div class="swal2-icon swal2-warning pulse-warning" style="display: block;">!</div>
	    <div class="swal2-icon swal2-info" style="display: none;">i</div>
	    <div class="swal2-icon swal2-success" style="display: none;"><span class="line tip"></span> <span class="line long"></span>
	        <div class="placeholder"></div>
	        <div class="fix"></div>
	    </div><img class="swal2-image" style="display: none;">
	    <h2>Are you sure</h2>
	    <div class="swal2-content" style="display: block;">Do you really want to delete this Status</div>
	    <input class="swal2-input" style="display: none;">
	    <input type="file" class="swal2-file" style="display: none;">
	    <div class="swal2-range" style="display: none;">
	        <output></output>
	        <input type="range">
	    </div>
	    <select class="swal2-select" style="display: none;"></select>
	    <div class="swal2-radio" style="display: none;"></div>
	    <label for="swal2-checkbox" class="swal2-checkbox" style="display: none;">
	        <input type="checkbox">
	    </label>
	    <textarea class="swal2-textarea" style="display: none;"></textarea>
	    <div class="swal2-validationerror" style="display: none;"></div>
	    <hr class="swal2-spacer" style="display: block;">
	    {{form_start(form)}}
              {{form_widget(form.Yes,{"attr":{"class":"swal2-confirm btn btn-success"}})}}
              <a href="{{path("app_status_index")}}" class="swal2-cancel btn btn-danger">Cancel</a>
		{{form_end(form)}}
	</div>
</div>
{% endblock%}

src/AppBundle/Resources/views/Status/gif_add.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-offset-1 col-md-10">
        <div class="card">
          <div class="card-header card-header-icon" data-background-color="rose">
            <i class="material-icons">gif</i>
          </div>
          <div class="card-content">
            <h4 class="card-title">New Gif</h4>
            {{form_start(form)}}
               <div class="form-group label-floating ">
                  <label class="control-label">Gif title</label>
                  {{form_widget(form.title,{"attr":{"class":"form-control"}})}}
                  <span class="validate-input">{{form_errors(form.title)}}</span>
              </div>
              <div class="form-group label-floating ">
                  <label class="control-label">Gif description</label>
                  {{form_widget(form.description,{"attr":{"class":"form-control"}})}}
                  <span class="validate-input">{{form_errors(form.description)}}</span>
              </div>
               <img src="{{asset("img/image_placeholder.jpg")}}" class="fileinput-preview thumbnail " id="img-preview">
                <div class="fileinput fileinput-new text-center" data-provides="fileinput" style="width: 100%;">
                    <div>
                        <a href="#" class="btn btn-rose btn-round btn-select" style="width: 100%;margin:0px;"><i class="material-icons">gif</i> SELECT GIF</a>
                    </div>
                    {{form_widget(form.filegif,{"attr":{"class":"file-hidden input-file img-selector","style":"   /* display: none; */height: 0px;width: 0px;position: absolute;"}})}}
                    <span class="validate-input">{{form_errors(form.filegif)}}</span>
               </div>
               <br>

              <div class="">
                    <label>
                      {{form_widget(form.enabled)}}  Enabled
                    </label>
              </div>
              <div class="">
                    <label>
                      {{form_widget(form.comment)}}  Enabled Comment
                    </label>
              </div>
              <br>
              {{form_label(form.categories,null,{label_attr:{"style":"font-size:16px"}})}} :
              <div>
                  <div class="row">
                 {% for field in form.categories %}
                      <label  style="background: #000;border-radius: 20px;padding: 5px;text-align: center;margin: 10px;color: white;font-weight: bold;padding-left: 20px;padding-right: 20px;">
                          {{ form_widget(field) }} {{ field.vars.label }}
                      </label>
                  {% endfor %}
                  </div>
              </div>
              <br>
              {{form_label(form.languages,null,{label_attr:{"style":"font-size:16px"}})}} :
              <div>
                  <div class="row">
                 {% for field in form.languages %}
                      <label  style="background: #000;border-radius: 20px;padding: 5px;text-align: center;margin: 10px;color: white;font-weight: bold;padding-left: 20px;padding-right: 20px;">
                          {{ form_widget(field) }} {{ field.vars.label }}
                      </label>
                  {% endfor %}
                  </div>
              </div>
                <div class="form-group label-floating ">
                    <label class="control-label">Gif tags (Ex:anim,art,hero)</label>
                    <br>
                    {{form_widget(form.tags,{"attr":{"class":"input-tags"}})}}
                    <span class="validate-input">{{form_errors(form.tags)}}</span>
                </div>
                <script>
                $('.input-tags').selectize({
                  persist: false,
                  createOnBlur: true,
                  create: true
                });
                </script>
              <br>
              <span class="pull-right"><a href="{{path("app_status_index")}}" class="btn btn-fill btn-yellow"><i class="material-icons">arrow_back</i> Cancel</a>{{form_widget(form.save,{attr:{"class":"btn btn-fill btn-rose"}})}}</span>
            {{form_end(form)}}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock%}

src/AppBundle/Resources/views/Status/view.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
<div class="container-fluid">
    <div class="row">
       <div class="col-sm-offset-1 col-md-10">
            <div class="card">
                <div class="card-header card-header-icon" data-background-color="rose">
                    {% if status.type =="image" %}
                    <i class="material-icons">image</i>
                    {% elseif status.type =="quote" %}
                    <i class="material-icons">format_quote</i>
                    {% elseif status.type =="gif" %}
                    <i class="material-icons">gif</i>
                    {% elseif status.type =="video" %}
                    <i class="material-icons">videocam</i>
                    {% elseif status.type =="fullscreen" %}
                    <i class="material-icons">videocam</i>
                    {% endif %}
                </div>
                <div class="card-content">
                    {% if status.type == "quote" %}
                        <br>
                        <br>
                        <br>
                        <div class="quote-view" style="background-color:#{{status.color}}">
                            {{status.clear}}
                        </div>
                    {% else %}
                        <h4 class="card-title">{{status.title}}</h4>
                        <p >{{status.description}}</p>
                    {% endif %}
                    {% if status.type == "video" or status.type == "fullscreen" %}
                        <video width="100%" src="{{asset(status.video.link)}}" controls>
                            <source id="video_here">
                            Your browser does not support HTML5 status.
                        </video>
                    {% endif %}
                    {% if status.media != null %}
                    <img src="{{asset(status.media.link)}}" class="fileinput-preview thumbnail " id="img-preview">
                    {% endif %}

                    <div style="text-align: center;">
                        <div class="reaction">
                            <span>
                                <img src="{{asset("img/like.png")}}" alt="">
                                <span class="label-reaction">{{status.like}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/love.png")}}" alt="">
                                <span class="label-reaction">{{status.love}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/angry.png")}}" alt="">
                                <span class="label-reaction">{{status.angry}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/haha.png")}}" alt="">
                                <span class="label-reaction">{{status.haha}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/sad.png")}}" alt="">
                                <span class="label-reaction">{{status.sad}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/wow.png")}}" alt="">
                                <span class="label-reaction">{{status.woow}}</span>
                            </span>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{% if status.enabled %}
                        <i class="material-icons" style="color:green;float:left">check_circle</i> <span class="check-label">Enabled</span>
                        {% else %}
                        <i class="material-icons" style="color:red;float:left">cancel</i> <span class="check-label">Disabled</span>
                        {% endif %}</div>
                    </div>
                     <div class="row">
                        <div class="col-md-6">{% if status.comment %}
                        <i class="material-icons" style="color:green;float:left">check_circle</i> <span class="check-label">Comment Enabled</span>
                        {% else %}
                        <i class="material-icons" style="color:red;float:left">cancel</i> <span class="check-label">Comment Disabled</span>
                        {% endif %}</div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <h4>Categories : </h4>
                        </div>
                        <div class="col-md-12" >
                            {% for category in status.categories %}
                                <span class="label label-rose " style="margin:5px;"> <b> {{category.title}} </b></span>  
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Languages : </h4>
                        </div>
                        <div class="col-md-12" >
                            {% for language in status.languages %}
                                <span class="label label-rose " style="margin:5px;background:#FF5722"> <b> {{language.language}} </b></span>  
                            {% endfor %}
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <span class="label label-rose col-md-6" style="font-size:16pt;padding:10px;background:#FF5722"> <b>{{status.viewsnumber}} </b></span>  
                        <span class="label label-rose col-md-6" style="font-size:16pt;padding:10px;background:#FF5722"> <b>{{status.downloadsnumber}} </b></span>  
                    </div>

                 </div>
                <div class="card-footer">
                    <div class="price">
                         <div class="wallpaper-logo" style="color:#040303" >
                        {% if status.user.image == "" %}
                            {{status.user.name}}
                        {% else %}
                            <img src="{{status.user.image}}" class="avatar-img" alt=""> 
                        {% endif %}
                         <span>{{status.user.name}}</span>
                     </div>
                    </div>
                    <div class="stats pull-right">
                       <div class="wallpaper-logo"  style="color:#040303" >{{status.created|ago}}</div>
                    </div>
                </div>
            </div>
            <div class="row">
            {% for comment in status.comments %}
                <div class="col-md-6">
                    <ul class="timeline timeline-simple">
                        <li class="timeline-inverted">
                            <div class="timeline-badge danger">
                                <img src="{{comment.user.image}}" class="img-profile">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <a href="{{path("user_user_edit",{id:comment.user.id})}}" title="">
                                        <span class="label label-danger">{{comment.user.name}}</span>
                                    </a>
                                    <span class="pull-right" >
                                        <a href="{{path("app_comment_delete",{id:comment.id,"status":"true"})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Delete">
                                            <i class="material-icons" style="color:red">delete</i>
                                        </a>
                                        {% if comment.enabled %}
                                            <a href="{{path("app_comment_hide",{id:comment.id})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Hide">
                                                 <i class="material-icons">visibility_off</i>
                                            </a>
                                        {% else %}                                      
                                            <a href="{{path("app_comment_hide",{id:comment.id})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Show">
                                                 <i class="material-icons">remove_red_eye</i>
                                            </a>
                                        {% endif %}
                                    </span>
                                </div>
                                <div class="timeline-body">
                                    <p>{{comment.contentclear}}</p>
                                </div>
                                <small class="pull-right label label-rose">
                                     <span>{{comment.created|ago}}</span>
                                </small>
                            </div>
                        </li>
                       
                    </ul>
                </div>
                {% else %}
                <div class="col-md-12" >
                    <div class="card"  style="margin-top: 0px;">
                        <div class="card-content">
                            <center><img src="{{asset("img/bg_empty.png")}}"  style="width: auto !important;" =""></center>
                            <br>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock%}